version: '3'
services:
 
 spider_app:
  image: pttcrawler
  environment:
   REDIS_HOST: redis
  ports:
   - '6381:6800'

 redis:
  image: redis
  ports:
   - '6380:6379'

 mongodb:
  image: sameersbn/mongodb:latest
  ports:
   - '6382:27017'
  volumes:
   - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:

